# Generated by Django 5.0.6 on 2024-06-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="cli_id", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("rut", models.CharField(max_length=12)),
                ("primer_apellido", models.CharField(max_length=50)),
                ("segundo_apellido", models.CharField(max_length=50)),
                ("telefono", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="game_id", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("precio", models.IntegerField()),
                ("genero", models.CharField(max_length=100)),
                ("fecha_lanzamiento", models.DateField()),
                ("descripcion", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="pedido_id", primary_key=True, serialize=False
                    ),
                ),
                ("nro_productos", models.IntegerField()),
                ("valor_total", models.IntegerField()),
                ("envio", models.BooleanField(default=True)),
                (
                    "f_cliente",
                    models.ForeignKey(
                        db_column="cli_FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.cliente",
                    ),
                ),
                (
                    "f_producto",
                    models.ManyToManyField(db_column="game_FK", to="tienda.game"),
                ),
            ],
        ),
    ]
