# Generated by Django 5.0.6 on 2024-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_remove_cliente_rut"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
