# Generated by Django 5.0.6 on 2024-07-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_cliente_direccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.IntegerField(null=True),
        ),
    ]
