# Generated by Django 5.0.6 on 2024-07-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0006_remove_pedido_f_producto_remove_pedido_valor_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="descripcion",
        ),
    ]
