# Generated by Django 5.0.6 on 2024-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0007_remove_game_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
