# Generated by Django 5.0.6 on 2024-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0008_alter_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="id",
            field=models.AutoField(
                db_column="game_id", primary_key=True, serialize=False
            ),
        ),
    ]
