# Generated by Django 5.0.6 on 2024-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0010_alter_game_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="precio",
        ),
        migrations.AddField(
            model_name="pedido",
            name="total_precio",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="record",
            name="precio_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="record",
            name="precio_uni",
            field=models.IntegerField(default=0),
        ),
    ]
