# Generated by Django 5.0.6 on 2024-07-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0011_remove_record_precio_pedido_total_precio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=50)),
                ("mensaje", models.CharField(max_length=500)),
                ("fecha_emision", models.DateField(auto_now_add=True)),
                ("email_emisor", models.CharField(max_length=80)),
                (
                    "f_cliente",
                    models.ForeignKey(
                        db_column="cliente_FK",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.cliente",
                    ),
                ),
            ],
        ),
    ]
