# Generated by Django 5.0.6 on 2024-07-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0012_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="respuesta",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
