# Generated by Django 5.0.6 on 2024-07-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0013_contact_respuesta"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="resuelta",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
