# Generated by Django 5.0.6 on 2024-07-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0014_contact_resuelta"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
    ]
