# Generated by Django 5.0.6 on 2024-07-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0015_game_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="valoracion",
            field=models.IntegerField(default=0),
        ),
    ]
